'use client';

import { Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import { STATES } from '@/data/states';
import { assess } from '@/lib/scoring';
import type { Technology, Tier } from '@/lib/types';
import contested from '@/data/contested-projects.json';

const TECH_LABEL: Record<Technology, string> = {
  wind: 'Wind',
  solar: 'Solar',
  battery: 'Battery Storage',
};

const TIER_LABEL: Record<Tier, string> = {
  federal: 'Federal',
  state: 'State',
  local: 'Local',
};

function MemoContent() {
  const params = useSearchParams();
  const stateCode = (params.get('state') ?? 'TX').toUpperCase();
  const tech = (params.get('tech') ?? 'solar') as Technology;

  const stateRecord = STATES.find((s) => s.code === stateCode);
  if (!stateRecord) {
    return <p style={{ padding: 40 }}>Unknown state: {stateCode}</p>;
  }
  const result = assess(stateRecord, tech);

  // Collect citations across all factors + mitigants, numbered, de-duplicated.
  const citations: string[] = [];
  const citeNum = (url?: string): number | null => {
    if (!url) return null;
    const existing = citations.indexOf(url);
    if (existing >= 0) return existing + 1;
    citations.push(url);
    return citations.length;
  };

  // Contested-projects summary for this state+tech.
  const stateContested = (contested as any).states[stateCode];
  const projects: any[] = stateContested?.projects?.[tech] ?? [];
  const cancelled = projects.filter((p) => p.status === 'Canceled').length;

  // Templated summary line — derived from data, not free-written.
  const topTier = [...result.tiers].sort((a, b) => b.score - a.score)[0];
  const summary = `${stateRecord.name} ${TECH_LABEL[tech].toLowerCase()} presents ${result.level} political & regulatory risk (score ${result.overallScore.toFixed(0)}/100), with the highest exposure at the ${TIER_LABEL[topTier.tier].toLowerCase()} tier.`;

  return (
    <div className="memo">
      <header>
        <p className="eyebrow">Political &amp; Regulatory Risk — Screening Assessment</p>
        <h1>
          {stateRecord.name} &mdash; {TECH_LABEL[tech]}
        </h1>
        <p className="meta">
          {result.level} Risk · {result.overallScore.toFixed(0)}/100 · Generated{' '}
          {new Date().toISOString().slice(0, 10)}
        </p>
      </header>

      <p className="summary">{summary}</p>

      {result.tiers.map((tier: any) => (
        <section key={tier.tier} className="tier">
          <h2>
            {TIER_LABEL[tier.tier as Tier]} <span className="score">{tier.score.toFixed(0)}/100</span>
          </h2>
          {tier.factors.length === 0 && <p className="muted">No applicable factors at this tier.</p>}
          {tier.factors.map((f: any) => {
            const n = citeNum(f.sourceUrl);
            return (
              <div key={f.id} className="factor">
                <p>
                  {f.status} {n && <sup>[{n}]</sup>}
                </p>
                {f.metric && (
                  <p className="basis">
                    <strong>Basis:</strong> {f.metric}
                    {f.basis ? ` (${f.basis})` : ''}
                  </p>
                )}
              </div>
            );
          })}
          {tier.mitigants?.map((m: any) => {
            const n = citeNum(m.sourceUrl);
            return (
              <div key={m.id} className="factor mitigant">
                <p>
                  <strong>Mitigant — {m.label}:</strong> {m.status} {n && <sup>[{n}]</sup>}
                </p>
              </div>
            );
          })}
        </section>
      ))}

      <section className="tier">
        <h2>Contested Projects on Record</h2>
        {projects.length === 0 ? (
          <p className="muted">
            No contested {TECH_LABEL[tech].toLowerCase()} projects on record (Sabin Center, data
            through 2024) — consistent with low local siting friction.
          </p>
        ) : (
          <p>
            {projects.length} contested {TECH_LABEL[tech].toLowerCase()} project
            {projects.length === 1 ? '' : 's'} on record ({cancelled} cancelled). Source: Sabin
            Center Opposition Report (data through 2024).
          </p>
        )}
      </section>

      {citations.length > 0 && (
        <section className="citations">
          <h2>Sources</h2>
          <ol>
            {citations.map((url, i) => (
              <li key={i}>{url}</li>
            ))}
          </ol>
        </section>
      )}

      <footer>
        <p>
          Screening assessment generated by political-risk-finder-PF. Scores are deterministic and
          sourced, not predictive of project outcomes. This is not investment, legal, or tax advice.
          See methodology for rubrics and limitations.
        </p>
      </footer>

      <style jsx>{`
        .memo {
          max-width: 720px;
          margin: 0 auto;
          padding: 48px 40px;
          color: #0f172a;
          font-family: Georgia, 'Times New Roman', serif;
          line-height: 1.5;
        }
        .eyebrow {
          text-transform: uppercase;
          letter-spacing: 0.08em;
          font-size: 11px;
          color: #64748b;
          font-family: system-ui, sans-serif;
          margin: 0 0 4px;
        }
        h1 {
          font-size: 26px;
          margin: 0 0 6px;
        }
        .meta {
          font-size: 13px;
          color: #475569;
          font-family: system-ui, sans-serif;
          margin: 0 0 24px;
          border-bottom: 1px solid #e2e8f0;
          padding-bottom: 16px;
        }
        .summary {
          font-size: 15px;
          font-style: italic;
          color: #334155;
          margin-bottom: 28px;
        }
        .tier {
          margin-bottom: 22px;
          page-break-inside: avoid;
        }
        h2 {
          font-size: 13px;
          text-transform: uppercase;
          letter-spacing: 0.06em;
          font-family: system-ui, sans-serif;
          color: #1e293b;
          border-bottom: 1px solid #cbd5e1;
          padding-bottom: 4px;
          margin: 0 0 10px;
        }
        h2 .score {
          float: right;
          color: #64748b;
          font-weight: normal;
        }
        .factor {
          margin-bottom: 10px;
          font-size: 14px;
        }
        .factor p {
          margin: 0;
        }
        .basis {
          font-size: 12px;
          color: #64748b;
          font-family: system-ui, sans-serif;
          margin-top: 2px;
        }
        .muted {
          font-size: 13px;
          color: #94a3b8;
          font-style: italic;
        }
        .mitigant {
          border-left: 3px solid #86efac;
          padding-left: 8px;
        }
        .citations {
          margin-top: 28px;
          border-top: 1px solid #e2e8f0;
          padding-top: 16px;
        }
        .citations ol {
          font-size: 11px;
          color: #475569;
          font-family: system-ui, sans-serif;
          padding-left: 20px;
          margin: 0;
        }
        .citations li {
          margin-bottom: 4px;
          word-break: break-all;
        }
        footer {
          margin-top: 32px;
          border-top: 1px solid #e2e8f0;
          padding-top: 12px;
          font-size: 11px;
          color: #94a3b8;
          font-family: system-ui, sans-serif;
        }
        footer p {
          margin: 0;
        }
        @media print {
          .memo {
            padding: 0;
          }
        }
      `}</style>
    </div>
  );
}

export default function MemoPage() {
  return (
    <Suspense fallback={<p style={{ padding: 40 }}>Loading…</p>}>
      <MemoContent />
    </Suspense>
  );
}
